# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
name: jmh
on:
  pull_request:
    branches:
      - master
jobs:
  jmh:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - name: Run JMH Benchmark Action
        uses: volodya-lombrozo/jmh-benchmark-action@main
        with:
          java-version: "11"
          base-ref: "master"
          benchmark-command: |
            mvn jmh:benchmark -Djmh.rf=json -Djmh.rff=benchmark.json
          benchmark-file: "benchmark.json"
