# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: titles
'on':
  schedule:
    - cron: '0 0 * * *'
  issues:
    types: [opened]
jobs:
  titles:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: horw/issue-title-ai@v0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          days-to-scan: 7
          skip-label: 'good-title'
          auto-update: true
          max-issues: 10
          model: gpt-4
